# Generated by Django 4.2.2 on 2023-06-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeapp', '0003_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code',
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=128, help_text='in kb'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=2, help_text='in seconds'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_code',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_stderr',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_stdout',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
