# Generated by Django 4.2.2 on 2023-06-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeapp', '0004_remove_submission_code_problem_memory_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
